'2201':
  "The creations of Jack and Dane from their time in the 2201 N 106th st apartment"
'5057':
  "Cocktails from our undergrad days at Ali's uncle's house"
Classics:
  "Classic drinks! You could order these in public and people will probably know what you mean"
Steely Dan:
  "Drinks inspired by Steely Dan songs and albums. Ask for a physical menu for extra ~zing~"
Zig Zag Clones:
  "Plagiarized from our favorite cocktail bar, The Zig Zag Cafe in Pike Place"
Prince:
  "Drinks inspires by Prince songs and albums. Jack is currently working on Purple Rain"
Lord of the Rings:
  "Ali uses old LoTR drinks to troubleshoot the website. Enjoy some (possibly bad) vintage!"