# Here she is, the main menu! Not completely sold yet that a yaml file is the best way to represent this, but I'm trying it out. Human readable and works well with the spell checker, but going to get long and can't auto sort
# Conventions - 
#     All cocktail names and liquor names are title case
#     All categories (i.e "collection" are lowercase)

# In VScode, "Ctrl + K Ctrl + 2" will fold everything nicely


Whiskey:
  ingredients:
    Four Roses Bourbon:
    Bulleit Rye:
    Sonoma Valley Cherrywood Rye:
    Famous Grouse Smokey Black:
    The Deacon Scotch:
Boulevardier:
  ingredients:
    Campari:
      units: oz
      amount: 1
    Sweet Vermouth:
      units: oz
      amount: 1
    Whiskey:
      units: oz
      amount: 1.25
  garnish: orange twist
  collection: classics
Anthracite Prospector:
  ingredients:
    Cognac:
      units: oz
      amount: 1.5
    Amaro Meletti:
      units: oz
      amount: 0.75
    Dark Creme de Cacao:
      units: oz
      amount: 0.75
  collection: 5057 main menu
The Highland Locust:
  ingredients:
    Famous Grouse Smoky Black:
      units: oz
      amount: 1
    Geneppy:
      units: oz
      amount: 0.5
    Brucato Woodlands:
      units: oz
      amount: 0.5
  collection: 2201 main menu
Pippin:
  ingredients:
    Brandy:
      units: oz
      amount: 1
    Creme de Cacao:
      units: oz
      amount: 0.5
    Falernum:
      units: oz
      amount: 0.5
    Peychaud's Bitters:
      unit: oz
      amount: 0.25
  collection: lord of the rings
Merry:
  ingredients:
    Brandy:
      units: oz
      amount: 1
    Triple sec:
      units: oz
      amount: 0.5
    Angostura Bitters:
      units: dash
      amount: 2
    Lime:
      units: oz
      amount: 0.5
  collection: lord of the rings