Test:
  collection: uncategorized
  ingredients: {}
  notes: ''
Test2:
  collection: uncategorized
  ingredients: {}
  notes: ''
test website:
  collection: uncategorized
  ingredients:
    Gin:
      amount: '1'
      units: oz
  notes: from pi
