Test_With_Output:
  collection: debug
  ingredients:
    Gin:
      amount: '1'
      units: oz
  notes: ''
Test Refactored:
  collection: debug
  ingredients:
    Rum:
      amount: '1'
      units: oz
    Falernum:
      amount: '0.5'
      units: oz
  notes: from pc
