Clearance:
  collection: Tags
  ingredients:
  - zignum_reposado
  - amaro_04
  - bols_triple_sec
  - high_west_bourye
  - pitu_cachaca
  - champagne
  - christian_brothers_vs
  - christian_brothers_vsop
  - red_blend_portugal
  notes: Ingredients that are in low supply, and should be encouraged by the randomizer.
