Vermouth:
  collection: Tags
  ingredients:
  - brovo_jammy
  - brovo_pink
  - blanc_vermouth
  - brovo_pretty
  - sweet_vermouth
  - dry_vermouth
  - brovo_witty
Sparkling Wine:
  collection: Tags
  ingredients:
  - brut
  - prosecco
Wine (Inclusive):
  collection: Tags
  ingredients:
  - Vermouth
  - Wine
  - port
  notes: Should probably also include normal wines like a general red or white if
    they ever make their way onto an ingredients list, but as yet they are not.
Wine:
  collection: Tags
  ingredients:
  - Red Wine
  - White Wine
  - Sparkling Wine
  notes: Someday we can add tags for types of red and white wines and blends and shit,
    but not this day. Also I guess this system isn't fortified against me buying a
    bottle of that sparkling Syrah
Red Wine:
  collection: Tags
  ingredients:
  - red_blend_portugal
  - port
  notes: Red, red wine
White Wine:
  collection: Tags
  ingredients: null
