Clearance:
    collection: Tags
    ingredients:
      - christian_brothers_vsop
      - pitu_cachaca
      - bols_triple_sec
      - zignum_reposado
      - amaro_04
    notes: Ingredients that are in low supply, and should be encouraged by the randomizer.
