Amaro:
  collection: Tags
  ingredients:
    Brovo Amaro: {}
    Brucato Amaro: {}
    Cynar: {}
    Gentian Amaro: {}
    amaro_angostura: {}
    aperol: {}
    byrrh: {}
    campari: {}
    cardamaro: {}
    meletti: {}
    nonino: {}
    reddit_aroma: {}
    rosso_amaro: {}
  notes: Include all amaros. Use high-level tags where possible
Base Spirits:
  collection: Tags
  ingredients:
    Brandy (Inclusive): {}
    Gin (Inclusive): {}
    Mezcal (Inclusive): {}
    Rum (Inclusive): {}
    Vodka (Inclusive): {}
    Whiskey (Inclusive): {}
  notes: Include only high-level tags here
Citrus:
  collection: Tags
  ingredients:
    Grapefruit Juice: {}
    Key Lime Juice: {}
    Lemon Juice: {}
    Lime Juice: {}
    Meyer Lemon Juice: {}
    Orange Juice: {}
  notes: Citrus
Liqueurs:
  collection: Tags
  ingredients:
    Fruit Liqueur: {}
    Herbal Liqueur: {}
    Misc Liqueur: {}
  notes: Include only high-level tags here
